version: "3"
services:
  oracle:
    image: truevoly/oracle-12c
    container_name: oracle
    ports:
      - "1521:1521"
      - "5500:5500"
    volumes:
      - oracle-data:/u01/app/oracle
volumes:
  oracle-data:
